spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/watch_with_me
    #    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

# JSON WebToken 설정
jwt:
  header: Authorization
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd6eXoxMjMxMjMxMjMxMjMxMjMxMzEyMzEyMzEzMTIzMTIzMTIzMTMxMjMxMzEzMTMxMjM
  accessTokenValidityInSeconds: 60 # 3600 60min


#logging.level:
#  org.hibernate.SQL: debug
