spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/watch_with_me
    #    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #       show_sql: true
        format_sql: true

naver:
  request_authorize_uri: https://nid.naver.com/oauth2.0/authorize
  request_token_uri: https://nid.naver.com/oauth2.0/token
  redirect_uri: http://localhost:8080/member/login
  client_id: SyFqItV5kCVSfgB_f0Lx
  client_secret: NSuHu1Zyx3

#logging.level:
#  org.hibernate.SQL: debug
