spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/watch_with_me
    #    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          naver:
            redirect_uri: http://localhost:8080/login
            client_id: SyFqItV5kCVSfgB_f0Lx
            client_secret: NSuHu1Zyx3
            authorization_grant_type: authorization_code
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user_info_uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

#logging.level:
#  org.hibernate.SQL: debug
