spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/watch_with_me
    #    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate.hbm2ddl.auto: update
    properties:
      hibernate:
        #       show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
